<?php

// $Id: disorder_gene_at.install $

function disorder_gene_at_install() {
    $t = get_t();

    $disorder_gene_at = array(
        'type' => 'disorder_gene_at',
        'name' => $t('Disorder-Gene association type'),
        'base' => 'node_content',
        'description' => $t('The Disorder-Gene association type content type.')
    );

    $content_type = node_type_set_defaults($disorder_gene_at);
    node_type_save($content_type);

    foreach (_disorder_gene_at_installed_fields() as $field) {
        field_create_field($field);
    }

    foreach (_disorder_gene_at_installed_instances() as $instance) {
        $instance['entity_type'] = 'node';
        $instance['bundle'] = $disorder_gene_at['type'];
        field_create_instance($instance);
    }

    variable_set('comment_disorder_gene_at', COMMENT_NODE_CLOSED);
    variable_set('node_options_disorder_gene_at', array('status'));
    variable_set('node_preview_disorder_gene_at', DRUPAL_DISABLED);
    variable_set('node_submitted_disorder_gene_at', FALSE);
}

function _disorder_gene_at_installed_fields() {
    $t = get_t();
    return array(
        'field_dgt_orphaid' => array(
            'field_name'	=> 'field_dgt_orphaid',
            'label'		=> $t('Orpha ID'),
            'cardinality'	=> 1,
            'type'		=> 'text',
            'settings'	=> array(
                'max_length' => 500,
            )
        ),
        'field_dgt_name' => array(
            'field_name'	=> 'field_dgt_name',
            'label'		=> $t('Name'),
            'cardinality'	=> 1,
            'type'		=> 'text',
            'settings'	=> array(
                'max_length' => 500,
            )
        )
    );
}

function _disorder_gene_at_installed_instances() {
    $t = get_t();
    return array(
        'field_dgt_orphaid' => array(
            'field_name' => 'field_dgt_orphaid',
            'label'       => $t('Orpha ID'),
            'cardinality' => 1,
            'widget'      => array(
                'type'    => 'text_textfield',
            ),
            'display' => array(
                'default' => array(
                    'type'  => 'hidden',
                    'label' => 'hidden',
                ),
                'full' => array(
                    'type' => 'hidden',
                    'label' => 'hidden',
                ),
                'teaser' => array(
                    'type' => 'hidden',
                    'label' => 'hidden',
                ),
            )
        ),
        'field_dgt_name' => array(
            'field_name' => 'field_dgt_name',
            'label'       => $t('Name'),
            'cardinality' => 1,
            'widget'      => array(
                'type'    => 'text_textfield',
            ),
            'display' => array(
                'default' => array(
                    'type'  => 'hidden',
                    'label' => 'hidden',
                ),
                'full' => array(
                    'type' => 'hidden',
                    'label' => 'hidden',
                ),
                'teaser' => array(
                    'type' => 'hidden',
                    'label' => 'hidden',
                ),
            )
        )
    );
}

function disorder_gene_at_uninstall() {
    $sql = 'SELECT nid FROM {node} n WHERE n.type = :type';
    $result = db_query($sql, array(':type' => 'disorder_gene_at'));
    $nids = array();
    foreach ($result as $row) {
        $nids[] = $row->nid;
    }

    node_delete_multiple($nids);

    foreach (array_keys(_disorder_gene_at_installed_fields()) as $field) {
        field_delete_field($field);
    }

    $instances = field_info_instances('node', 'disorder_gene_at');
    foreach ($instances as $instance_name => $instance) {
        field_delete_instance($instance);
    }

    node_type_delete('disorder_gene_at');

    field_purge_batch(1000);
}
