<?php
// $Id: disorder_gene.install $


function disorder_gene_install() {
    $t = get_t();

    $disorder_gene = array(
        'type' => 'disorder_gene',
        'name' => $t('Disorder-Gene'),
        'base' => 'node_content',
        'description' => $t('The Disorder-Gene content type.')
    );

    $content_type = node_type_set_defaults($disorder_gene);
    node_type_save($content_type);

    foreach (_disorder_gene_installed_fields() as $field) {
        field_create_field($field);
    }

    foreach (_disorder_gene_installed_instances() as $instance) {
        $instance['entity_type'] = 'node';
        $instance['bundle'] = $disorder_gene['type'];
        field_create_instance($instance);
    }

    variable_set('comment_disorder_gene', COMMENT_NODE_CLOSED);
    variable_set('node_options_disorder_gene', array('status'));
    variable_set('node_preview_disorder_gene', DRUPAL_DISABLED);
    variable_set('node_submitted_disorder_gene', FALSE);
}

function _disorder_gene_installed_fields() {
    $t = get_t();
    return array(
        'field_disgene_gene' => array(
            'field_name'	=> 'field_disgene_gene',
            'label'		=> $t('Gene'),
            'cardinality'	=> 1,
            'type'		=> 'entityreference',
            'settings'	=> array(
                'referenceable_types' => array(
                    'gene' => 'gene'
                )
            )
        ),
        'field_disgene_disorder' => array(
            'field_name'	=> 'field_disgene_disorder',
            'label'		=> $t('Disorder'),
            'cardinality'	=> 1,
            'type'		=> 'entityreference',
            'settings'	=> array(
                'referenceable_types' => array(
                    'disorder' => 'disorder'
                )
            )
        ),
        'field_disgene_as' => array(
            'field_name'	=> 'field_disgene_as',
            'label'		=> $t('Association status'),
            'cardinality'	=> 1,
            'type'		=> 'entityreference',
            'settings'	=> array(
                'referenceable_types' => array(
                    'disorder_gene_as' => 'disorder_gene_as'
                )
            )
        ),
        'field_disgene_at' => array(
            'field_name'	=> 'field_disgene_at',
            'label'		=> $t('Association type'),
            'cardinality'	=> 1,
            'type'		=> 'entityreference',
            'settings'	=> array(
                'referenceable_types' => array(
                    'disorder_gene_at' => 'disorder_gene_at'
                )
            )
        ),
    );
}

function _disorder_gene_installed_instances() {
    $t = get_t();
    return array(
        'field_disgene_gene' => array(
            'field_name'	=> 'field_disgene_gene',
            'label'		=> $t('Gene'),
            'cardinality'	=> 1,
            'widget'		=> array(
                'type'    => 'entityreference_autocomplete',
            ),
            'display' => array(
                'default' => array(
                    'type'  => 'hidden',
                    'label' => 'hidden',
                ),
                'full' => array(
                    'type' => 'hidden',
                    'label' => 'hidden',
                ),
                'teaser' => array(
                    'type' => 'hidden',
                    'label' => 'hidden',
                ),
            )
        ),
        'field_disgene_disorder' => array(
            'field_name'	=> 'field_disgene_disorder',
            'label'		=> $t('Disorder'),
            'cardinality'	=> 1,
            'widget'		=> array(
                'type'    => 'entityreference_autocomplete',
            ),
            'display' => array(
                'default' => array(
                    'type'  => 'hidden',
                    'label' => 'hidden',
                ),
                'full' => array(
                    'type' => 'hidden',
                    'label' => 'hidden',
                ),
                'teaser' => array(
                    'type' => 'hidden',
                    'label' => 'hidden',
                ),
            )
        ),
        'field_disgene_as' => array(
            'field_name'	=> 'field_disgene_as',
            'label'		=> $t('Association status'),
            'cardinality'	=> 1,
            'widget'		=> array(
                'type'    => 'entityreference_autocomplete',
            ),
            'display' => array(
                'default' => array(
                    'type'  => 'hidden',
                    'label' => 'hidden',
                ),
                'full' => array(
                    'type' => 'hidden',
                    'label' => 'hidden',
                ),
                'teaser' => array(
                    'type' => 'hidden',
                    'label' => 'hidden',
                ),
            )
        ),
        'field_disgene_at' => array(
            'field_name'	=> 'field_disgene_at',
            'label'		=> $t('Association type'),
            'cardinality'	=> 1,
            'widget'		=> array(
                'type'    => 'entityreference_autocomplete',
            ),
            'display' => array(
                'default' => array(
                    'type'  => 'hidden',
                    'label' => 'hidden',
                ),
                'full' => array(
                    'type' => 'hidden',
                    'label' => 'hidden',
                ),
                'teaser' => array(
                    'type' => 'hidden',
                    'label' => 'hidden',
                ),
            )
        ),
    );
}

function disorder_gene_uninstall() {
    $sql = 'SELECT nid FROM {node} n WHERE n.type = :type';
    $result = db_query($sql, array(':type' => 'disorder_gene'));
    $nids = array();
    foreach ($result as $row) {
        $nids[] = $row->nid;
    }

    node_delete_multiple($nids);

    foreach (array_keys(_disorder_gene_installed_fields()) as $field) {
        field_delete_field($field);
    }

    $instances = field_info_instances('node', 'disorder_gene');
    foreach ($instances as $instance_name => $instance) {
        field_delete_instance($instance);
    }

    node_type_delete('disorder_gene');

    field_purge_batch(1000);
}
