<?php
// $Id: gene.install $


function gene_install() {
    $t = get_t();

    $gene = array(
        'type' => 'gene',
        'name' => $t('Gene'),
        'base' => 'node_content',
        'description' => $t('The Gene content type.')
    );

    $content_type = node_type_set_defaults($gene);
    node_type_save($content_type);

    foreach (_gene_installed_fields() as $field) {
        field_create_field($field);
    }

    foreach (_gene_installed_instances() as $instance) {
        $instance['entity_type'] = 'node';
        $instance['bundle'] = $gene['type'];
        field_create_instance($instance);
    }

    variable_set('comment_gene', COMMENT_NODE_CLOSED);
    variable_set('node_options_gene', array('status'));
    variable_set('node_preview_gene', DRUPAL_DISABLED);
    variable_set('node_submitted_gene', FALSE);
}

function _gene_installed_fields() {
    $t = get_t();
    return array(
        'field_gene_orphaid' => array(
            'field_name'	=> 'field_gene_orphaid',
            'label'		=>$t('Orpha ID'),
            'cardinality'	=> 1,
            'type'		=> 'text',
            'settings'	=> array(
                'max_length' => 500,
            )
        ),
        'field_gene_orphanumber' => array(
            'field_name'	=> 'field_gene_orphanumber',
            'label'		=> $t('Orpha Number'),
            'cardinality'	=> 1,
            'type'		=> 'text',
            'settings'	=> array(
                'max_length' => 500,
            )
        ),
        'field_gene_name' => array(
            'field_name'	=> 'field_gene_name',
            'label'		=> $t('Name'),
            'cardinality'	=> 1,
            'type'		=> 'text',
            'settings'	=> array(
                'max_length' => 500,
            )
        ),
        'field_gene_symbol' => array(
            'field_name'	=> 'field_gene_symbol',
            'label'		=> $t('Symbol'),
            'cardinality'	=> 1,
            'type'		=> 'text',
            'settings'	=> array(
                'max_length' => 500,
            )
        ),
        'field_gene_synonym' => array(
            'field_name'	=> 'field_gene_synonym',
            'label'		=> $t('Synonym'),
            'cardinality'	=> -1,
            'type'		=> 'text',
            'settings'	=> array(
                'max_length' => 500,
            )
        ),
        'field_gene_er' => array(
            'field_name'	=> 'field_gene_er',
            'label'		=> $t('External reference'),
            'cardinality'	=> -1,
            'type'		=> 'entityreference',
            'settings'	=> array(
                'referenceable_types' => array(
                    'external_reference' => 'external_reference'
                )
            )
        ),
        'field_gene_disgene' => array(
            'field_name'	=> 'field_gene_disgene',
            'label'		=> $t('Disorder-Gene association'),
            'cardinality'	=> -1,
            'type'		=> 'entityreference',
            'settings'	=> array(
                'referenceable_types' => array(
                    'disorder_gene' => 'disorder_gene'
                )
            )
        ),
    );
}

function _gene_installed_instances() {
    $t = get_t();
    return array(
        'field_gene_orphaid' => array(
            'field_name' => 'field_gene_orphaid',
            'label'       => $t('Orpha ID'),
            'cardinality' => 1,
            'widget'      => array(
                'type'    => 'text_textfield',
            ),
            'display' => array(
                'default' => array(
                    'type'  => 'hidden',
                    'label' => 'hidden',
                ),
                'full' => array(
                    'type' => 'hidden',
                    'label' => 'hidden',
                ),
                'teaser' => array(
                    'type' => 'hidden',
                    'label' => 'hidden',
                ),
            )
        ),
        'field_gene_orphanumber' => array(
            'field_name' => 'field_gene_orphanumber',
            'label'       => $t('Orpha Number'),
            'cardinality' => 1,
            'widget'      => array(
                'type'    => 'text_textfield',
            ),
            'display' => array(
                'default' => array(
                    'type'  => 'hidden',
                    'label' => 'hidden',
                ),
                'full' => array(
                    'type' => 'hidden',
                    'label' => 'hidden',
                ),
                'teaser' => array(
                    'type' => 'hidden',
                    'label' => 'hidden',
                ),
            )
        ),
        'field_gene_name' => array(
            'field_name' => 'field_gene_name',
            'label'       => $t('Name'),
            'cardinality' => 1,
            'widget'      => array(
                'type'    => 'text_textfield',
            ),
            'display' => array(
                'default' => array(
                    'type'  => 'hidden',
                    'label' => 'hidden',
                ),
                'full' => array(
                    'type' => 'hidden',
                    'label' => 'hidden',
                ),
                'teaser' => array(
                    'type' => 'hidden',
                    'label' => 'hidden',
                ),
            )
        ),
        'field_gene_symbol' => array(
            'field_name' => 'field_gene_symbol',
            'label'       => $t('Symbol'),
            'cardinality' => 1,
            'widget'      => array(
                'type'    => 'text_textfield',
            ),
            'display' => array(
                'default' => array(
                    'type'  => 'hidden',
                    'label' => 'hidden',
                ),
                'full' => array(
                    'type' => 'hidden',
                    'label' => 'hidden',
                ),
                'teaser' => array(
                    'type' => 'hidden',
                    'label' => 'hidden',
                ),
            )
        ),
        'field_gene_synonym' => array(
            'field_name' => 'field_gene_synonym',
            'label'       => $t('Synonym'),
            'cardinality' => -1,
            'widget'      => array(
                'type'    => 'text_textfield',
            ),
            'display' => array(
                'default' => array(
                    'type'  => 'hidden',
                    'label' => 'hidden',
                ),
                'full' => array(
                    'type' => 'hidden',
                    'label' => 'hidden',
                ),
                'teaser' => array(
                    'type' => 'hidden',
                    'label' => 'hidden',
                ),
            )
        ),
        'field_gene_er' => array(
            'field_name'	=> 'field_gene_er',
            'label'		=> $t('External reference'),
            'cardinality'	=> -1,
            'widget'		=> array(
                'type'    => 'entityreference_autocomplete',
            ),
            'display' => array(
                'default' => array(
                    'type'  => 'hidden',
                    'label' => 'hidden',
                ),
                'full' => array(
                    'type' => 'hidden',
                    'label' => 'hidden',
                ),
                'teaser' => array(
                    'type' => 'hidden',
                    'label' => 'hidden',
                ),
            )
        ),
        'field_gene_disgene' => array(
            'field_name'	=> 'field_gene_disgene',
            'label'		=> $t('Disorder-Gene association'),
            'cardinality'	=> -1,
            'widget'		=> array(
                'type'    => 'entityreference_autocomplete',
            ),
            'display' => array(
                'default' => array(
                    'type'  => 'hidden',
                    'label' => 'hidden',
                ),
                'full' => array(
                    'type' => 'hidden',
                    'label' => 'hidden',
                ),
                'teaser' => array(
                    'type' => 'hidden',
                    'label' => 'hidden',
                ),
            )
        ),
    );
}

function gene_uninstall() {
    $sql = 'SELECT nid FROM {node} n WHERE n.type = :type';
    $result = db_query($sql, array(':type' => 'gene'));
    $nids = array();
    foreach ($result as $row) {
        $nids[] = $row->nid;
    }

    node_delete_multiple($nids);

    foreach (array_keys(_gene_installed_fields()) as $field) {
        field_delete_field($field);
    }

    $instances = field_info_instances('node', 'gene');
    foreach ($instances as $instance_name => $instance) {
        field_delete_instance($instance);
    }

    node_type_delete('gene');

    field_purge_batch(1000);
}
